# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - dorna2_arm_controller

  dorna2_arm_controller:
    type: FollowJointTrajectory
    joints:
      - Joint_0
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
    action_ns: follow_joint_trajectory
    default: true